### ISSUE TITLE
Cannot find `mingw-w64-i686-ncurses`

### ISSUE THREAD

**Issue by da-liii** [slowphil/mingw-w64-guile1.8#1]
https://github.com/slowphil/mingw-w64-guile1.8/blob/b4a3d30ead961a2baf6c45a372835c2ae84b5c10/PKGBUILD#L17

Remove the prefix may fix it.

**Comment by da-liii** [comment]
However, after I fixed the ncurses depend problem, there are still other problems to fix when:

```
MINGW_INSTALLS=mingw32 makepkg-mingw -sLi --noconfirm
```

Finally, I download the pre-compiled tar.xz and hack on the `.PKGINFO` file, just change 

```
depend = mingw-w64-i686-ncurses>=5.7
```
to

```
depend = ncurses
```

**Comment by slowphil** [comment]
Sorry for the long absence of reaction. I just tested today building that package either in an existing MSYS2/mingw-w64 setup dating back from 2020-02 or in a fresh setup using [msys2-x86_64-20201109.exe](https://repo.msys2.org/distrib/x86_64/msys2-x86_64-20201109.exe) and both worked. I guess it was a temporary problem. Closing.
